In [ ]:
# Setting up a custom stylesheet in IJulia
file = open("style.css") # A .css file in the same folder as this notebook file
styl = read(file, String) # Read the file
HTML("$styl") # Output as HTML

<h1> Ebola and Wikipedia: Loading publicly available data using Julia </h1>

<h2>In this lecture</h2>

- [Outcome](#Outcome)
- [Wikipedia data on the West African EVD epidemic](#Wikipedia-data-on-the-West-African-EVD-epidemic)
- [Loading the DelimitedFiles package](#Loading-the-DelimitedFiles-package)
- [Using readdlm() to load a .csv file](#Using-readdlm-to-load-a-.csv-file)

[Back to the top](#In-this-lecture)

<h2>Outcome</h2>

After this lecture, you will be able to
- Find data on the West African EVD epidemic online
- Load a Julia package
- Use readdlm() to load this data from a .csv file

[Back to the top](#In-this-lecture)

<h2>Wikipedia data on the West African EVD epidemic</h2>

Wikipedia has many excellent articles on Ebola. We will be using one with fairly complete data on the timeline of cases: https://en.wikipedia.org/wiki/West_African_Ebola_virus_epidemic_timeline_of_reported_cases_and_deaths

Go there now, please, and navigate until you see a table that looks like this:

<img src="Week2_Lecture2_1-Wikipedia-EVD-cases.png" alt="(Screenshot of wikipedia table of WA EVD cases)">


[Back to the top](#In-this-lecture)

We have provided the data as a file named wikipediaEVDraw.csv. The ".csv" extension indicates that it is a comma-separated file, and the "raw" in the filename indicates that the data are imported as is, without any changes.

If you would like to learn how to create .csv files from tables on the web, please go the optional lecture "How to export web tables to .csv files".

[Back to the top](#In-this-lecture)

<h2>Loading the DelimitedFiles package</h2>

Here is a special Julia moment: our first time to load a package explicitly. 

As noted in an earlier lecture, Julia consists of some basics that are always loaded, plus extensions that can be additionally loaded. One of these is the DelimitedFiles package, which is part of the standard library, but in order to use it, you have to load it. To do so is very simple: you just enter ``using DelimitedFiles``. We need it to read the .csv file of EVD data.

But *why* do we need to load the DelimitedFiles package? Why isn't it available out of the box, when you start up Julia?

The reason is efficiency, of two kinds. First there is starting-up efficiency, then there is functionality efficiency.

Starting-up efficiency is achieved by not cluttering the starting-up process with all kinds of features that aren't essential to starting up. Most programs go a little beyond the absolute minimum, though, and Julia is no exception. However, although .csv files are very often used, they are only one of many kinds of delimited files. It is part of the Julia philosophy to put related functionalities together in one place, so the methods for reading and writing delimited files are all in the DelimitedFiles package. This makes it both quite large and full of features that are only rarely needed---in other words, it makes DelimitedFiles incompatible with starting-up efficiency.

Functionality efficiency is achieved by making it easy to find the functionality you need, quick to write the code you need, and for this code to run optimally fast. How this is achieved is an advanced topic, but one thing is clear: making it possible read a .csv file in out-of-the box Julia does not necessarily help with any of this.

What you see here is a strong element of Julia's design, which values consistency and efficiency above convenience.

[Back to the top](#In-this-lecture)

<h2>Using readdlm to load a .csv file</h2>

Now we can start using Julia again. In a new notebook for you Week 2 Julia code, enter and execute the line below:

In [1]:
using DelimitedFiles
wikiEVDraw = DelimitedFiles.readdlm("wikipediaEVDraw.csv", ',')  # getting quotes right is important!

54×9 Matrix{Any}:
 "25 Nov 2015"  28637  11314  3804  2536  …  4808     14122     3955
 "18 Nov 2015"  28634  11314  3804  2536     4808     14122     3955
 "11 Nov 2015"  28635  11314  3805  2536     4808     14122     3955
 "4 Nov 2015"   28607  11314  3810  2536     4808     14089     3955
 "25 Oct 2015"  28539  11298  3806  2535     4808     14061     3955
 "18 Oct 2015"  28476  11298  3803  2535  …  4808     14001     3955
 "11 Oct 2015"  28454  11297  3800  2534     4808     13982     3955
 "27 Sep 2015"  28388  11296  3805  2533     4808     13911     3955
 "20 Sep 2015"  28295  11295  3800  2532     4808     13823     3955
 "13 Sep 2015"  28220  11291  3792  2530     4808     13756     3953
 "6 Sep 2015"   28147  11291  3792  2530  …  4808     13683     3953
 "30 Aug 2015"  28073  11290  3792  2529     4808     13609     3953
 "16 Aug 2015"  27952  11284  3786  2524     4808     13494     3952
 ⋮                                        ⋱                     
 "9 Aug 2014"    183

The ``readdlm()`` function is Julia's way to read any file that consists of lines separated into data items with a delimiter of some sort. In fact, the very word "readdlm" is an abbreviation of "read-with-a-delimiter". 

Notice five things
- We loaded the DelimitedFiles package with ``using DelimitedFiles``.
- In order to use ``readdlm()``, we have to say that it sits in the DelimitedFiles package, using the dot syntax ``DelimitedFiles.readdlm()``. This use$^1$ of dot syntax for referencing an object that sits inside another object is also used in languages like C++ and Java. 
- We have used a variable to contain the data from the file (you could change the name, though, if you like)
- The file name is given as a string, using double quotes
- The delimeter is given as a character, using single quotes

Finally, we see from the output the type the data: after they have been stored in the variable as an array, the elements are of type ``Any``. This is not good for computation---in particular, for modelling we need the data in terms of days since the start of the epidemic. Our next job is to convert the strings in columnn one into integers which give number of days since 22 March 2014.

$^1$ The dot syntax for using ``readdlm()`` can be avoided, but to present that we would need to discuss modules, and that is a relatively advanced topic that is not important for this course.

In [2]:
?readdlm()

```
readdlm(source, T::Type; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt", Int64)
4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

julia> readdlm("delim_file.txt", Float64)
4×2 Matrix{Float64}:
 1.0  5.0
 2.0  6.0
 3.0  7.0
 4.0  8.0

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, T::Type; options...)
```

The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',', Float64)
4×2 Matrix{Float64}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")
```

---

```
readdlm(source; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt")
4×2 Matrix{Any}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar; options...)
```

The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Matrix{Float64}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> z = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x z], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Matrix{Any}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, eol::AbstractChar; options...)
```

If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

---

```
readdlm(source, delim::AbstractChar, T::Type, eol::AbstractChar; header=false, skipstart=0, skipblanks=true, use_mmap, quotes=true, dims, comments=false, comment_char='#')
```

Read a matrix from the source where each line (separated by `eol`) gives one row, with elements separated by the given delimiter. The source can be a text file, stream or byte array. Memory mapped files can be used by passing the byte array representation of the mapped segment as source.

If `T` is a numeric type, the result is an array of that type, with any non-numeric elements as `NaN` for floating-point types, or zero. Other useful values of `T` include `String`, `AbstractString`, and `Any`.

If `header` is `true`, the first row of data will be read as header and the tuple `(data_cells, header_cells)` is returned instead of only `data_cells`.

Specifying `skipstart` will ignore the corresponding number of initial lines from the input.

If `skipblanks` is `true`, blank lines in the input will be ignored.

If `use_mmap` is `true`, the file specified by `source` is memory mapped for potential speedups. Default is `true` except on Windows. On Windows, you may want to specify `true` if the file is large, and is only read once and not written to.

If `quotes` is `true`, columns enclosed within double-quote (") characters are allowed to contain new lines and column delimiters. Double-quote characters within a quoted field must be escaped with another double-quote.  Specifying `dims` as a tuple of the expected rows and columns (including header, if any) may speed up reading of large files.  If `comments` is `true`, lines beginning with `comment_char` and text following `comment_char` in any line are ignored.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end

julia> readdlm("delim_file.txt", '\t', Int, '\n')
4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

julia> rm("delim_file.txt")
```


[Back to the top](#In-this-lecture)